
- name: "clear old cron tasks"
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: delete all game crons
      shell: rm -f /etc/cron.d/the_tale*

    - name: delete all service crons
      shell: rm -f /etc/cron.d/tt_*

- name: "preinstall cron tasks"
  hosts: all
  become: yes
  become_user: root
  tasks:
    - cron:
        name: HOME
        env: yes
        cron_file: the_tale
        user: the_tale
        job: /home/the_tale/

    - cron:
        name: PATH
        env: yes
        cron_file: the_tale
        user: the_tale
        job: "$PATH:/home/the_tale/current/venv/bin/"

    - cron:
        name: soft currency rollback
        cron_file: tt_soft_currency
        minute: 0
        user: tt_soft_currency
        job: /home/tt_soft_currency/current/venv/bin/tt_bank_rollback_hanged_transactions -c /etc/tt_soft_currency/config.json

    - cron:
        name: soft currency rollback
        cron_file: tt_soft_currency
        minute: 0
        user: tt_soft_currency
        job: /home/tt_soft_currency/current/venv/bin/tt_bank_remove_old_transactions -c /etc/tt_soft_currency/config.json -t 86400

    - cron:
        name: clean personal messages
        cron_file: tt_personal_messages
        minute: 0
        user: tt_personal_messages
        job: /home/tt_personal_messages/current/venv/bin/tt_personal_messages_clean -c /etc/tt_personal_messages/config.json

    - cron:
        name: process data protection tasks
        cron_file: tt_data_protector
        minute: 15
        hour: 0
        user: tt_data_protector
        job: /home/tt_data_protector/current/venv/bin/tt_data_protector_process_tasks -c /etc/tt_data_protector/config.json

    - cron:
        name: clans statistics sync
        cron_file: the_tale
        minute: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin clans_sync_statistics --settings the_tale.settings

    - cron:
        name: clans points adding
        cron_file: the_tale
        minute: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin clans_give_points --interval 3600 --settings the_tale.settings

    - cron:
        name: clans currencies rollback
        cron_file: tt_clans_currencies
        minute: 0
        user: tt_clans_currencies
        job: /home/tt_clans_currencies/current/venv/bin/tt_bank_rollback_hanged_transactions -c /etc/tt_clans_currencies/config.json

    - cron:
        name: clans free quests reset
        cron_file: the_tale
        minute: 0
        hour: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin clans_reset_free_quests --settings the_tale.settings

    - cron:
        name: emissaries step
        cron_file: the_tale
        minute: 1
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin emissaries_step --settings the_tale.settings

    - cron:
        name: emissaries monitoring
        cron_file: the_tale
        minute: "*/5"
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin emissaries_monitoring --settings the_tale.settings

    - cron:
        name: process emissaries days cycle
        cron_file: the_tale
        minute: 2
        hour: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin emissaries_process_day --settings the_tale.settings

    - cron:
        name: periodicaly apply bills
        cron_file: the_tale
        minute: "*/10"
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin bills_apply --settings the_tale.settings

    - cron:
        name: do highlevel step
        cron_file: the_tale
        minute: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin game_highlevel_step --settings the_tale.settings

    - cron:
        name: portal cleaning
        cron_file: the_tale
        minute: 0
        hour: 1
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin portal_clean --settings the_tale.settings

    - cron:
        name: sessions cleaning
        cron_file: the_tale
        minute: 0
        hour: 2
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin clearsessions --settings the_tale.settings

    - cron:
        name: remove personal messages from system user
        cron_file: the_tale
        minute: 0
        hour: 3
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin personal_messages_remove_system_messages --settings the_tale.settings

    - cron:
        name: clean removed linguistics templates
        cron_file: the_tale
        minute: 0
        hour: 4
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin linguistics_clean_removed_templates --settings the_tale.settings

    - cron:
        name: removed expired access tokens
        cron_file: the_tale
        minute: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin third_party_remove_expired_access_tokens --settings the_tale.settings

    - cron:
        name: update game statistics
        cron_file: the_tale
        minute: 0
        hour: 5
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin statistics_complete --settings the_tale.settings

    - cron:
        name: refresh cdns
        cron_file: the_tale
        minute: 0
        hour: "*/4"
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin portal_refresh_cdns --settings the_tale.settings

    - cron:
        name: update might
        cron_file: the_tale
        minute: 0
        hour: 6
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin accounts_calculate_might --settings the_tale.settings

    - cron:
        name: update ratings
        cron_file: the_tale
        minute: 0
        hour: 7
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin ratings_recalculate_ratings --settings the_tale.settings


    - cron:
        name: new day actions
        cron_file: the_tale
        minute: 0
        hour: 8
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin portal_new_day_actions --settings the_tale.settings

    - cron:
        name: send notifications about expired premiums
        cron_file: the_tale
        minute: 30
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin accounts_send_premium_expired_notifications --settings the_tale.settings

    - cron:
        name: monitor protectorates
        cron_file: the_tale
        minute: 3
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin places_monitor_protectorates --settings the_tale.settings
