
tt_domain: local.the-tale
tt_test_enviroment: True
tt_log_level: debug
tt_site_workers: 1
tt_install_nginx: True
tt_install_postfix: True
tt_python: python3.8
tt_python_venv_command: /usr/bin/python3.8 -m venv

tt_postfix_virtual_aliases: {}

tt_authorized_keys: []

internal_repositories: []

tt_services:
  the_tale:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/deworld/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/questgen/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_logic/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_calendar/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/the_tale/"}
  tt_diary:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_diary/"}
  tt_personal_messages:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_personal_messages/"}
  tt_storage:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_storage/"}
  tt_market:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_market/"}
  tt_soft_currency:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_bank/"}
  tt_players_timers:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_timers/"}
    custom:
        secret: test.secret
        sleep_if_no_timers_interval: 0.1
        delay_before_callback_retry: 1.0
        max_delay_before_callback_retry: 3600
        max_simultaneously_requests: 5

        types:
          0:
            url: http://localhost:8000/game/cards/tt/take-card-callback

  tt_personal_impacts:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_impacts/"}
    custom:
        scale_chunk_size: 100
  tt_crowd_impacts:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_impacts/"}
    custom:
        scale_chunk_size: 100
  tt_job_impacts:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_impacts/"}
    custom:
        scale_chunk_size: 100
  tt_fame_impacts:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_impacts/"}
    custom:
        scale_chunk_size: 100

  tt_game_chronicle:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_events_log/"}

  tt_clans_chronicle:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_events_log/"}

  tt_money_spendings:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_impacts/"}
    custom:
        scale_chunk_size: 100
        log_single_impacts: False
        log_actors_impacts: False
        log_target_impacts: True

  tt_players_properties:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_properties/"}

  tt_clans_properties:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_properties/"}

  tt_matchmaker:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_matchmaker/"}

  tt_clans_currencies:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_bank/"}

  tt_emissaries_impacts:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_impacts/"}
    custom:
        scale_chunk_size: 100

  tt_places_effects:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_effects/"}

  tt_emissaries_events_currencies:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_bank/"}

  tt_emissaries_events_uniquer:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_uniquer/"}

  tt_discord:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_discord/"}


tt_RAM: 4096
tt_postgresql_maintenance_work_mem: 32MB # 256MB
tt_postgresql_max_worker_processes: 1    # ???? ~ cores number div 2? or just cores number

tt_backups: None

tt_datadog_api_key: None