# Generated by Django 2.2.8 on 2020-04-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discord_id', models.BigIntegerField(null=True, unique=True)),
                ('game_id', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Nick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(db_index=True, null=True)),
                ('account', models.ForeignKey(db_column='account', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tt_discord.Account')),
            ],
            options={
                'db_table': 'nicknames',
            },
        ),
        migrations.CreateModel(
            name='BindCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expire_at', models.DateTimeField(db_index=True)),
                ('account', models.ForeignKey(db_column='account', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tt_discord.Account', unique=True)),
            ],
            options={
                'db_table': 'bind_codes',
            },
        ),
    ]
