# Generated by Django 2.2.8 on 2020-05-01 09:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_discord', '0002_auto_20200430_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(db_index=True, null=True)),
                ('account', models.ForeignKey(db_column='account', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tt_discord.Account')),
            ],
            options={
                'db_table': 'game_data',
                'unique_together': {('account', 'type')},
            },
        ),
        migrations.DeleteModel(
            name='Nick',
        ),
    ]
