# Generated by Django 2.2.8 on 2020-05-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_discord', '0003_auto_20200501_0947'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='gamedata',
            index_together={('updated_at', 'synced_at')},
        ),
    ]
