# Generated by Django 2.2.8 on 2020-05-02 15:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_discord', '0004_auto_20200502_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
