# Generated by Django 2.2.8 on 2020-05-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_discord', '0005_auto_20200502_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindcode',
            name='account',
            field=models.OneToOneField(db_column='account', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tt_discord.Account'),
        ),
    ]
